version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"               # location of package.json
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    automerged_updates: false
    labels:
      - "dependencies"
